### ISSUE TITLE
Wish move flink-zeromq to bahir-flink 

### ISSUE THREAD

**Issue by yew1eb** [omaralvarez/flink-zeromq#1]
Hi @omaralvarez,
Currently, The Apache Flink community is adding new connectors to the [bahir-flink repository](https://github.com/apache/bahir-flink). I observed that flink-zeromq has not been updated for a long time.
Are you willing to contribute flink-zeromq to the flink community?
if yes,  I can help to migrate flink-zeromq to the bahir-flink repository, and update flink-zeromq  consistent with the current flink version.

Regards,
Hai Zhou

**Comment by omaralvarez** [comment]
Yes, I would have no problem contributing this to Bahir. Right now my main concern is that the code has not been updated, and I would need to do some work for it to be well documented and more robust. 

I haven't had a lot of time as of late, but I would not mind trying to give this project some love. I am not familiar with Bahir, so I probably need to get up to speed on that first.

**Comment by soumyakantiroychowdhury** [comment]
@omaralvarez I tested your ZMQSource implementation with Flink version 1.3.2 and it is working fine. Hope it helps!
